name: YAML Validator CI

on:
  push:
    paths:
      - 'services/yaml-validator/**'
    branches:
      - main
  pull_request:
    paths:
      - 'services/yaml-validator/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r services/yaml-validator/app/requirements.txt
          pip install pytest
      - name: Run tests
        run: |
          pytest -q services/yaml-validator/tests

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/yaml-validator:${{ github.sha }} services/yaml-validator
          docker tag ${{ secrets.DOCKER_USERNAME }}/yaml-validator:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/yaml-validator:latest

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/yaml-validator:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/yaml-validator:latest
